### ISSUE TITLE
关于模板内置方法调用方法，ts并不会提示参数类型错误

### ISSUE THREAD

**Issue by chenchenpp** [Jack-cool/ts-vue#19]
你好，有个问题请教你。在vue2的template模板里绑定事件，事件传递参数，如果参数的类型定义的与方法不一致，ts并不会提示错误。这是vue2本身的限制，还是需要额外的配置呢？期望大佬能够解答
![D06F61~1](https://user-images.githubusercontent.com/33083284/130572396-4c8a7bec-c452-4515-8068-7af811a1c6e2.PNG)

**Comment by Cosen95** [comment]
你可以先参考我这个项目配置一下，然后再试试看
